#!/usr/bin/env node
'use strict';
// The acceptance gate. Design rules, in order of importance:
//
// 1. RE-RUN, don't read. Every report consumed here is regenerated by
//    invoking its producer checker fresh, then schema-validated. A stale,
//    hand-edited, or repo-planted report JSON can never satisfy this gate.
// 2. REGISTRY-DRIVEN. The set of producers comes from registry.json, not a
//    hardcoded list — a new skill registered as a consumer feed cannot be
//    forgotten here (v0.4 forgot backend entirely).
// 3. FAIL CLOSED. Producer missing => not_evaluated (caps at CONDITIONAL).
//    Producer crashed or emitted invalid output => fail (BLOCK).
// 4. BUILDER != ACCEPTOR. Without --acceptor-context separate, the verdict
//    is capped at CONDITIONAL: the context that built cannot self-SHIP.
//
// Usage: node accept-check.js --root <dir> --acceptor-context separate|same
//        [--strict] [--out <file>] [--no-write]

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { corePaths } = require('./resolve-core.cjs');
const core = corePaths();
const { parseArgs } = require(path.join(core.lib, 'args.cjs'));
const { classify, conditionMet } = require(path.join(core.lib, 'classify.cjs'));
const { readText, hasHeading, check, runCli } = require(path.join(core.lib, 'report.cjs'));
const { validate } = require(path.join(core.lib, 'schema.cjs'));
const registry = require(core.registry);

function checkDocumentArtifact(root, artifact, checks) {
  const p = path.join(root, artifact.file);
  if (!fs.existsSync(p)) {
    checks.push(check(`A-${artifact.id}`, 'fail', `required document ${artifact.file} is missing`));
    return;
  }
  const text = readText(p);
  const missing = (artifact.requiredHeadings || []).filter((h) => !hasHeading(text, h));
  checks.push(missing.length > 0
    ? check(`A-${artifact.id}`, 'fail', `${artifact.file} missing heading(s): ${missing.join(', ')}`)
    : check(`A-${artifact.id}`, 'pass', artifact.file));
}

function checkReportArtifact(root, artifact, checks) {
  const id = `D-${artifact.producer}`;
  const script = path.join(core.suiteRoot, ...artifact.producerScript.split('/'));
  if (!fs.existsSync(script)) {
    checks.push(check(id, 'not_evaluated',
      `producer skill "${artifact.producer}" is not installed (${artifact.producerScript})`));
    return;
  }
  // Fresh run — never trust what's on disk.
  const res = spawnSync(process.execPath, [script, '--root', root], {
    encoding: 'utf8',
    maxBuffer: 20 * 1024 * 1024,
  });
  if (res.error || res.status === null || res.status >= 2) {
    checks.push(check(id, 'fail',
      `producer checker crashed (exit ${res.status ?? res.error?.message}); a broken gate is not a passing gate`));
    return;
  }
  let report;
  try {
    report = JSON.parse(res.stdout);
  } catch {
    checks.push(check(id, 'fail', 'producer checker emitted unparseable output'));
    return;
  }
  const schemaPath = path.join(core.schemas, path.basename(artifact.schema));
  const errors = validate(JSON.parse(readText(schemaPath)), report);
  if (errors.length > 0) {
    checks.push(check(id, 'fail', `producer report failed schema validation: ${errors.slice(0, 3).join('; ')}`));
    return;
  }
  if (report.verdict === 'BLOCK') {
    const failed = report.checks.filter((c) => c.status === 'fail').map((c) => c.id);
    checks.push(check(id, 'fail', `${artifact.producer} verdict BLOCK (${failed.join(', ')})`));
  } else if (report.verdict === 'CONDITIONAL') {
    const open = report.checks.filter((c) => c.status === 'not_evaluated').map((c) => c.id);
    checks.push(check(id, 'not_evaluated', `${artifact.producer} verdict CONDITIONAL (open: ${open.join(', ')})`));
  } else {
    checks.push(check(id, 'pass', `${artifact.producer} verdict SHIP`));
  }
}

function run(root, args) {
  const cls = classify(root);
  const checks = [];

  // Builder != acceptor.
  const ctx = args['acceptor-context'] || 'same';
  checks.push(ctx === 'separate'
    ? check('A-independent', 'pass', 'acceptance ran in a separate context from the build')
    : check('A-independent', 'not_evaluated',
        'acceptance ran in the builder context; re-run with --acceptor-context separate in a fresh session — SHIP is unreachable until then'));

  for (const artifact of registry.artifacts) {
    if (!artifact.consumers.includes('product-acceptance')) continue;
    if (!conditionMet(artifact.requiredWhen, cls)) continue;
    if (artifact.kind === 'document') checkDocumentArtifact(root, artifact, checks);
    else if (artifact.kind === 'report') checkReportArtifact(root, artifact, checks);
  }
  return checks;
}

module.exports = { run };

if (require.main === module) {
  runCli({
    skill: 'product-acceptance',
    reportFile: 'acceptance-report.json',
    evidenceDir: registry.evidenceDir,
    runFn: run,
    argv: process.argv.slice(2),
    parseArgs,
  });
}
