#!/usr/bin/env node
'use strict';
// The acceptance gate. Design rules, in order of importance:
//
// 1. RE-RUN, don't read. Every report consumed here is regenerated by
//    invoking its producer checker fresh (with --no-write, so acceptance
//    never mutates the project it's auditing), then schema-validated. A
//    stale, hand-edited, or repo-planted report JSON can never satisfy
//    this gate.
// 2. REGISTRY-DRIVEN. The set of producers comes from registry.json, not a
//    hardcoded list — a new skill registered with acceptanceGated: true
//    cannot be forgotten here (v0.4 forgot backend entirely).
// 3. FAIL CLOSED. Producer missing => not_evaluated (caps at CONDITIONAL).
//    Producer crashed, hung past its timeout, or emitted invalid output
//    => fail (BLOCK).
// 4. BUILDER != ACCEPTOR. Without --acceptor-context separate, the verdict
//    is capped at CONDITIONAL: the context that built cannot self-SHIP.
//
// Usage: node accept-check.js --root <dir> --acceptor-context separate|same
//        [--runtime-verified]
//        [--strict] [--out <file>] [--no-write]

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { corePaths } = require('./resolve-core.cjs');
const core = corePaths();
const { parseArgs } = require(path.join(core.lib, 'args.cjs'));
const { classify, conditionMet } = require(path.join(core.lib, 'classify.cjs'));
const { readText, sectionHasContent, check, runCli, computeVerdict } = require(path.join(core.lib, 'report.cjs'));
const { validate } = require(path.join(core.lib, 'schema.cjs'));
const registry = require(core.registry);

const PRODUCER_TIMEOUT_MS = 60_000;

function checkDocumentArtifact(root, artifact, checks) {
  const p = path.join(root, artifact.file);
  if (!fs.existsSync(p)) {
    checks.push(check(`A-${artifact.id}`, 'fail', `required document ${artifact.file} is missing`));
    return;
  }
  const text = readText(p);
  const missing = (artifact.requiredHeadings || []).filter((h) => !sectionHasContent(text, h));
  checks.push(missing.length > 0
    ? check(`A-${artifact.id}`, 'fail', `${artifact.file} missing heading(s): ${missing.join(', ')}`)
    : check(`A-${artifact.id}`, 'pass', `${artifact.file}${provenanceSuffix(text)}`));
}

// A document reconstructed from the implementation cannot be evidence about
// the implementation — it records what the code does, not what it should do,
// and it will agree with the code every time because it was read off it.
//
// Declared as a line in the document: `Provenance: stated-by-human` /
// `derived-from-session` / `reconstructed-from-code`. Undeclared is treated
// as unknown, not as human — assuming the safer value is how a reconstructed
// contract would pass as intent.
const PROVENANCE_RE = /^\s*(?:>\s*)?(?:\*\*)?provenance(?:\*\*)?\s*[:—-]\s*([a-z-]+)/im;
const HUMAN_ANCHORED = new Set(['stated-by-human', 'human', 'authored-by-human']);

function provenanceOf(text) {
  const match = PROVENANCE_RE.exec(text);
  return match ? match[1].toLowerCase() : 'undeclared';
}

function provenanceSuffix(text) {
  const value = provenanceOf(text);
  return value === 'undeclared' ? ' (provenance undeclared)' : ` (provenance: ${value})`;
}

// Compares the producer skill's install-marker version against this skill's
// own — catches a stale/mixed-version vendor after a partial suite upgrade,
// or a same-named-but-foreign directory impersonating a sibling skill. In a
// dev checkout (no markers at all) this is a no-op: nothing to compare, so
// nothing is flagged.
function readMarkerVersion(skillDir) {
  const p = path.join(skillDir, '.agent-skills-install.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(readText(p)).version || null;
  } catch {
    return null;
  }
}

function producerVersionMismatch(producerScriptAbsPath) {
  const producerSkillDir = path.dirname(path.dirname(producerScriptAbsPath));
  const producerVersion = readMarkerVersion(producerSkillDir);
  const ownSkillDir = path.dirname(__dirname);
  const ownVersion = readMarkerVersion(ownSkillDir);
  if (producerVersion === null || ownVersion === null) return null; // can't compare — allow
  if (producerVersion !== ownVersion) {
    return `sibling skill installed at version ${producerVersion}, this skill at ${ownVersion} — reinstall to sync`;
  }
  return null;
}

function checkReportArtifact(root, artifact, checks) {
  const id = `D-${artifact.producer}`;
  const script = path.join(core.suiteRoot, ...artifact.producerScript.split('/'));
  if (!fs.existsSync(script)) {
    checks.push(check(id, 'not_evaluated',
      `producer skill "${artifact.producer}" is not installed (${artifact.producerScript})`));
    return;
  }
  const mismatch = producerVersionMismatch(script);
  if (mismatch) {
    checks.push(check(id, 'not_evaluated', mismatch));
    return;
  }
  // Fresh run, never write into the project under audit — never trust what's
  // on disk, and never leave it dirtier than the acceptance run found it.
  const res = spawnSync(process.execPath, [script, '--root', root, '--no-write'], {
    encoding: 'utf8',
    maxBuffer: 20 * 1024 * 1024,
    timeout: PRODUCER_TIMEOUT_MS,
    killSignal: 'SIGKILL',
  });
  if (res.error || res.status === null || res.status >= 2) {
    const reason = res.signal ? `killed by ${res.signal} (timeout or hang)` : `exit ${res.status ?? res.error?.message}`;
    checks.push(check(id, 'fail',
      `producer checker crashed or did not complete (${reason}); a broken gate is not a passing gate`));
    return;
  }
  let report;
  try {
    report = JSON.parse(res.stdout);
  } catch {
    checks.push(check(id, 'fail', 'producer checker emitted unparseable output'));
    return;
  }
  const schemaPath = path.join(core.schemas, path.basename(artifact.schema));
  const errors = validate(JSON.parse(readText(schemaPath)), report);
  if (errors.length > 0) {
    checks.push(check(id, 'fail', `producer report failed schema validation: ${errors.slice(0, 3).join('; ')}`));
    return;
  }
  // Recompute the verdict from the producer's own checks rather than trusting
  // its self-declared `verdict` field. Re-running the producer instead of
  // reading its report off disk removes trust in stale FILES; branching on a
  // value the producer wrote ABOUT ITSELF put that trust straight back one
  // level down. A producer emitting {verdict:'SHIP', checks:[{status:'fail'}]}
  // was recorded as passing with the failing check in hand.
  //
  // A disagreement is itself a finding: the producer is either buggy or drifted
  // from the shared verdict rule, and either way its report can't be relied on.
  const recomputed = computeVerdict(report.checks);
  if (recomputed !== report.verdict) {
    checks.push(check(id, 'fail',
      `${artifact.producer} reported verdict ${report.verdict} but its own checks compute to ${recomputed} — ` +
      `a producer that disagrees with itself is not a passing gate`));
    return;
  }
  if (recomputed === 'BLOCK') {
    const failed = report.checks.filter((c) => c.status === 'fail').map((c) => c.id);
    checks.push(check(id, 'fail', `${artifact.producer} verdict BLOCK (${failed.join(', ')})`));
  } else if (recomputed === 'CONDITIONAL') {
    const open = report.checks.filter((c) => c.status === 'not_evaluated').map((c) => c.id);
    checks.push(check(id, 'not_evaluated', `${artifact.producer} verdict CONDITIONAL (open: ${open.join(', ')})`));
  } else {
    checks.push(check(id, 'pass', `${artifact.producer} verdict SHIP`));
  }
}

function run(root, args) {
  const cls = classify(root, { evidenceDir: registry.evidenceDir });
  const checks = [];

  // Builder != acceptor.
  const ctx = args['acceptor-context'] || 'same';
  checks.push(ctx === 'separate'
    ? check('A-independent', 'pass', 'acceptance ran in a separate context from the build')
    : check('A-independent', 'not_evaluated',
        'acceptance ran in the builder context; re-run with --acceptor-context separate in a fresh session — SHIP is unreachable until then'));

  // Static evidence cannot prove that the product starts or its critical path
  // works. This explicit assertion is reserved for an independent acceptor
  // after a real run/build/test walkthrough; without it automated SHIP is
  // deliberately unreachable.
  checks.push(ctx === 'separate' && args['runtime-verified']
    ? check('A-runtime', 'pass', 'independent acceptor asserted a successful runtime/build/test walkthrough')
    : check('A-runtime', 'not_evaluated',
        'runtime behavior was not independently verified; run the product and its critical path, then add --runtime-verified'));

  // Intent has to come from somewhere outside the code. If PRODUCT.md was
  // reconstructed from the implementation — or does not say — then the chain
  // is a mirror: acceptance can still judge whether this is consistent and
  // well built, but not whether it is the right product. That is a
  // not_evaluated, which caps the verdict at CONDITIONAL, rather than a
  // failure: nothing here is wrong, it is unverifiable from inside.
  const contract = registry.artifacts.find((a) => a.id === 'product-contract');
  const contractPath = contract ? path.join(root, contract.file) : null;
  if (contractPath && fs.existsSync(contractPath)) {
    const declared = provenanceOf(readText(contractPath));
    checks.push(HUMAN_ANCHORED.has(declared)
      ? check('A-intent-anchored', 'pass', `${contract.file} provenance: ${declared}`)
      : check('A-intent-anchored', 'not_evaluated',
          `${contract.file} provenance is "${declared}" — intent is not anchored outside the implementation, so this verdict covers consistency and build quality, not whether it is the right product`));
  }

  for (const artifact of registry.artifacts) {
    if (!artifact.acceptanceGated) continue;
    if (!conditionMet(artifact.requiredWhen, cls)) continue;
    if (artifact.kind === 'document') checkDocumentArtifact(root, artifact, checks);
    else if (artifact.kind === 'report') checkReportArtifact(root, artifact, checks);
  }
  return checks;
}

module.exports = { run };

if (require.main === module) {
  const artifact = registry.artifacts.find((a) => a.producer === 'product-acceptance' && a.kind === 'report');
  runCli({
    skill: 'product-acceptance',
    reportFile: path.basename(artifact.file),
    evidenceDir: registry.evidenceDir,
    runFn: run,
    argv: process.argv.slice(2),
    parseArgs,
  });
}
